HEATMAP_IRRELEVANT_VARIABLES = {
    "Row",
    "Col",
    "Target",
    "NUCLEAR PARIMETER",
    "CELL PARIEMETER",
    "Field",
}

RESTRICT_HEATMAP_VARIABLES = True
HEATMAP_TARGET_VARIABLE = "CHRONO_ORDER"
